'use strict';
/**
 * Diagram Library Constants. 
 *
 * Author: Paul Daniell <paul.d@mm.st>
 *
 **/
 

define(['jquery', 'underscore', 'backbone', 'kinetic' ],
function($, _, Backbone, Kinetic) {
	var DiagramConstants = {
		
		// ControlPoint Defaults
		// ---------------------
			
		CONTROLPOINT_DEFAULT_WIDTH: 9, 
	
		CONTROLPOINT_DEFAULT_HEIGHT: 9, 

		CONTROLPOINT_DEFAULT_FILL: "#fff",
		
		CONTROLPOINT_DEFAULT_MOUSEOVERFILL: "#000", 
		
		CONTROLPOINT_DEFAULT_STROKE: "#000", 
		
		CONTROLPOINT_DEFAULT_STROKEWIDTH: 0.5,
		
		CONTROLPOINT_DEFAULT_VISIBILITY: null, 
		
		CONTROLPOINT_DEFAULT_MOUSECLICKFILL: "red", 
		
		NORTH: 0, 
		
		SOUTH: 1, 
		
		EAST: 2, 
		
		WEST: 3, 
		
		NORTHWEST: 4, 		

		SOUTHWEST: 5, 		
		
		SOUTHEAST: 6, 
		
		NORTHEAST: 7, 

		
		// Vertex Defaults
		// ---------------
		 
		VERTEX_DEAFULT_WIDTH: 60,
				 
		VERTEX_DEFAULT_HEIGHT: 60, 
		
		VERTEX_DEFAULT_INNERFILL: "#ddd",
		
		VERTEX_DEFAULT_OUTERFILL: "#fff", 
		
		VERTEX_DEFAULT_INNERSTROKE: "#999", 
		
		VERTEX_DEFAULT_OUTERSTROKE: "#999", 
		
		VERTEX_DEFAULT_INNERSTROKEWIDTH: 1,
		
		VERTEX_DEFAULT_OUTERSTROKEWIDTH: 2, 
		
		VERTEX_DEFAULT_DRAGGABLE: true, 
		
		VERTEX_DEFAULT_DOUBLESTROKE: false, 
		
		VERTEX_DEFAULT_INNERCIRCLE_DELTA: 12, 
		
		VERTEX_DEFAULT_LABEL_FONT: "Computer Modern Serif", 
		
		VERTEX_DEFAULT_LABEL_FONTSIZE: 18, 
		
		VERTEX_DEFAULT_LABEL_FONTSTYLE:"normal",
		
		VERTEX_DEFAULT_LABEL_FILL: "#000", 
		
		VERTEX_DEFAULT_LABEL_X: -6, 
		
		VERTEX_DEFAULT_LABEL_Y: -6,
		
		VERTEX_DEFAULT_START_RADIUS: 12, 
		
		VERTEX_DEFAULT_START_COLOR: "red", 
		
		VERTEX_DEFAULT_STARTINDICATORVISIBLE: false, 
		
		// Arc Defaults
		// ------------
		
		ARC_DEFAULT_MH_PADDING: 25,
		
		ARC_DEFAULT_STROKE: "red",
		
		ARC_DEFAULT_SELECTEDSTROKE: "green", 
		
		ARC_DEFAULT_STROKEWIDTH:2, 
		
		ARC_DEFAULT_LINECAP: "round", 
		
		ARC_DEFAULT_LINEJOIN: "round", 
		
		ARCARROWHEAD_DEFAULT_FILL: "red",
		
		ARCARROWHEAD_DEFAULT_STROKE: "red",
		
		ARCARROWHEAD_DEFAULT_SELECTEDFILL: "green", 

		ARCARROWHEAD_DEFAULT_SELECTEDSTROKE: "green", 
		
		ARCARROWHEAD_DEFAULT_STROKEWIDTH: 1,
		
		ARCARROWHEAD_DEFAULT_ORIENTATION: 0,  
		
		ARCARROWHEAD_DEFAULT_WIDTH: 15, 
		
		ARCARROWHEAD_DEFAULT_HEIGHT: 15, 
		
		ARCLABEL_DEFAULT_HEIGHT: 30, 
		
		ARCLABEL_DEFAULT_WIDTH: 30, 
		
		ARCLABEL_DEFAULT_STROKEWIDTH: 2,
		
		ARCLABEL_DEFAULT_STROKE: "#333",
		
		ARCLABEL_DEFAULT_SELECTEDSTROKE: "green", 
		
		ARCLABEL_DEFAULT_FILL: "#fff",
		
		ARCLABEL_DEFAULT_LABEL_OFFSETX: -8,
		
		ARCLABEL_DEFAULT_LABEL_OFFSETY: -5,
		
		ARCLABEL_DEFAULT_LABEL_FONTCOLOR: "#000",
		
		ARCLABEL_DEFAULT_LABEL_FONT: "Computer Modern Serif", 
		
		ARCLABEL_DEFAULT_LABEL_FONTSIZE: 10, 
		
		ARCLABEL_DEFAULT_LABEL_FONTSTYLE:"normal"
		
		
	}; 
	
	return DiagramConstants; 
	
	
}); 